prediction_step: 20

arm_predictor:
  adapt: 1
  lambda: 0.999 # Forgetting factor
  EMA_v: 0
  EMA_p: 0
  
wrist_predictor:
  # Adaptation params
  adapt: 1
  lambda: 0.999 # Forgetting factor
  EMA_v: 0
  EMA_p: 0.3
  enable_multi_epoch: 0
  multi_epoch_epsilon1: 0.5
  multi_epoch_epsilon2: 1

  # Network hyper params
  model_path: 'trained_model/model725.tar' #model_10in_1layer_good/model49.tar' 
  input_seq_len: 10
  input_size: 3 # input: 10x3
  hidden_size: 128
  num_layers: 1
  output_size: 3 # output (1xn): 1x3


Train_wrist_predictor:
  # True: train from scratch using the hyper params in wrist_predictor and then evaluate. False: evaluate the model specified by model_path
  train: True
  save_model: True # True: save trained model in the output_folder
  output_folder: 'trained_model/'
  model_path: 'trained_model/model725.tar' 
  learning_rate: 0.0001
  num_epochs: 1000